# Generated by Django 3.2.8 on 2021-10-22 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('idTicket', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200, verbose_name='Titulo')),
                ('descripcion', models.TextField(max_length=500, verbose_name='Descripcion del ticket')),
                ('estado', models.CharField(choices=[('0', 'Abierto'), ('1', 'Pendiente'), ('2', 'En proceso'), ('3', 'Resuelto'), ('4', 'Cerrado')], max_length=1, verbose_name='Estado del ticket')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
